import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import "@liveblocks/react-ui/styles.css";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "4-LOOP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}